// flow-typed signature: 1669792cc46a361dd2d2f2f976c83c41
// flow-typed version: <<STUB>>/react-dependent-script_v^1.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dependent-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dependent-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dependent-script/es/index' {
  declare module.exports: any;
}

declare module 'react-dependent-script/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dependent-script/es/index.js' {
  declare module.exports: $Exports<'react-dependent-script/es/index'>;
}
declare module 'react-dependent-script/lib/index.js' {
  declare module.exports: $Exports<'react-dependent-script/lib/index'>;
}
