// flow-typed signature: 7c0a8b3211531cef0725045d2c54db16
// flow-typed version: <<STUB>>/react-widgets_v^4.4.5/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-widgets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-widgets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-widgets/dist/react-widgets' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/AddToListOption' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/AutocompleteListItem' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Button' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Calendar' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/CalendarView' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Century' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Combobox' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/ComboboxInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/configure' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DatePicker' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DateTimePicker' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DateTimePickerInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Decade' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DropdownList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/DropdownListInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Footer' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Header' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Icon' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/index' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Input' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/List' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Listbox' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/ListOption' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/ListOptionGroup' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/messages' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Month' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Multiselect' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/MultiselectInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/MultiselectTag' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/MultiselectTagList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/NumberInput' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/NumberPicker' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Popup' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Select' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/SelectList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/SelectListItem' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/SlideDownTransition' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/SlideTransitionGroup' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/TimeList' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/TimePicker' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/_' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/configuration' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/dataHelpers' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/dates' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/Filter' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/focusManager' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/getAccessors' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/interaction' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/localizers' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/Props' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/PropTypes' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/reduceToListState' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/scrollManager' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/util/widgetHelpers' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Widget' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/WidgetPicker' {
  declare module.exports: any;
}

declare module 'react-widgets/lib/Year' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-widgets/dist/react-widgets.js' {
  declare module.exports: $Exports<'react-widgets/dist/react-widgets'>;
}
declare module 'react-widgets/lib/AddToListOption.js' {
  declare module.exports: $Exports<'react-widgets/lib/AddToListOption'>;
}
declare module 'react-widgets/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-widgets/lib/Autocomplete'>;
}
declare module 'react-widgets/lib/AutocompleteListItem.js' {
  declare module.exports: $Exports<'react-widgets/lib/AutocompleteListItem'>;
}
declare module 'react-widgets/lib/Button.js' {
  declare module.exports: $Exports<'react-widgets/lib/Button'>;
}
declare module 'react-widgets/lib/Calendar.js' {
  declare module.exports: $Exports<'react-widgets/lib/Calendar'>;
}
declare module 'react-widgets/lib/CalendarView.js' {
  declare module.exports: $Exports<'react-widgets/lib/CalendarView'>;
}
declare module 'react-widgets/lib/Century.js' {
  declare module.exports: $Exports<'react-widgets/lib/Century'>;
}
declare module 'react-widgets/lib/Combobox.js' {
  declare module.exports: $Exports<'react-widgets/lib/Combobox'>;
}
declare module 'react-widgets/lib/ComboboxInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/ComboboxInput'>;
}
declare module 'react-widgets/lib/configure.js' {
  declare module.exports: $Exports<'react-widgets/lib/configure'>;
}
declare module 'react-widgets/lib/DatePicker.js' {
  declare module.exports: $Exports<'react-widgets/lib/DatePicker'>;
}
declare module 'react-widgets/lib/DateTimePicker.js' {
  declare module.exports: $Exports<'react-widgets/lib/DateTimePicker'>;
}
declare module 'react-widgets/lib/DateTimePickerInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/DateTimePickerInput'>;
}
declare module 'react-widgets/lib/Decade.js' {
  declare module.exports: $Exports<'react-widgets/lib/Decade'>;
}
declare module 'react-widgets/lib/DropdownList.js' {
  declare module.exports: $Exports<'react-widgets/lib/DropdownList'>;
}
declare module 'react-widgets/lib/DropdownListInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/DropdownListInput'>;
}
declare module 'react-widgets/lib/Footer.js' {
  declare module.exports: $Exports<'react-widgets/lib/Footer'>;
}
declare module 'react-widgets/lib/Header.js' {
  declare module.exports: $Exports<'react-widgets/lib/Header'>;
}
declare module 'react-widgets/lib/Icon.js' {
  declare module.exports: $Exports<'react-widgets/lib/Icon'>;
}
declare module 'react-widgets/lib/index.js' {
  declare module.exports: $Exports<'react-widgets/lib/index'>;
}
declare module 'react-widgets/lib/Input.js' {
  declare module.exports: $Exports<'react-widgets/lib/Input'>;
}
declare module 'react-widgets/lib/List.js' {
  declare module.exports: $Exports<'react-widgets/lib/List'>;
}
declare module 'react-widgets/lib/Listbox.js' {
  declare module.exports: $Exports<'react-widgets/lib/Listbox'>;
}
declare module 'react-widgets/lib/ListOption.js' {
  declare module.exports: $Exports<'react-widgets/lib/ListOption'>;
}
declare module 'react-widgets/lib/ListOptionGroup.js' {
  declare module.exports: $Exports<'react-widgets/lib/ListOptionGroup'>;
}
declare module 'react-widgets/lib/messages.js' {
  declare module.exports: $Exports<'react-widgets/lib/messages'>;
}
declare module 'react-widgets/lib/Month.js' {
  declare module.exports: $Exports<'react-widgets/lib/Month'>;
}
declare module 'react-widgets/lib/Multiselect.js' {
  declare module.exports: $Exports<'react-widgets/lib/Multiselect'>;
}
declare module 'react-widgets/lib/MultiselectInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/MultiselectInput'>;
}
declare module 'react-widgets/lib/MultiselectTag.js' {
  declare module.exports: $Exports<'react-widgets/lib/MultiselectTag'>;
}
declare module 'react-widgets/lib/MultiselectTagList.js' {
  declare module.exports: $Exports<'react-widgets/lib/MultiselectTagList'>;
}
declare module 'react-widgets/lib/NumberInput.js' {
  declare module.exports: $Exports<'react-widgets/lib/NumberInput'>;
}
declare module 'react-widgets/lib/NumberPicker.js' {
  declare module.exports: $Exports<'react-widgets/lib/NumberPicker'>;
}
declare module 'react-widgets/lib/Popup.js' {
  declare module.exports: $Exports<'react-widgets/lib/Popup'>;
}
declare module 'react-widgets/lib/Select.js' {
  declare module.exports: $Exports<'react-widgets/lib/Select'>;
}
declare module 'react-widgets/lib/SelectList.js' {
  declare module.exports: $Exports<'react-widgets/lib/SelectList'>;
}
declare module 'react-widgets/lib/SelectListItem.js' {
  declare module.exports: $Exports<'react-widgets/lib/SelectListItem'>;
}
declare module 'react-widgets/lib/SlideDownTransition.js' {
  declare module.exports: $Exports<'react-widgets/lib/SlideDownTransition'>;
}
declare module 'react-widgets/lib/SlideTransitionGroup.js' {
  declare module.exports: $Exports<'react-widgets/lib/SlideTransitionGroup'>;
}
declare module 'react-widgets/lib/TimeList.js' {
  declare module.exports: $Exports<'react-widgets/lib/TimeList'>;
}
declare module 'react-widgets/lib/TimePicker.js' {
  declare module.exports: $Exports<'react-widgets/lib/TimePicker'>;
}
declare module 'react-widgets/lib/util/_.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/_'>;
}
declare module 'react-widgets/lib/util/configuration.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/configuration'>;
}
declare module 'react-widgets/lib/util/dataHelpers.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/dataHelpers'>;
}
declare module 'react-widgets/lib/util/dates.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/dates'>;
}
declare module 'react-widgets/lib/util/Filter.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/Filter'>;
}
declare module 'react-widgets/lib/util/focusManager.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/focusManager'>;
}
declare module 'react-widgets/lib/util/getAccessors.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/getAccessors'>;
}
declare module 'react-widgets/lib/util/interaction.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/interaction'>;
}
declare module 'react-widgets/lib/util/localizers.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/localizers'>;
}
declare module 'react-widgets/lib/util/Props.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/Props'>;
}
declare module 'react-widgets/lib/util/PropTypes.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/PropTypes'>;
}
declare module 'react-widgets/lib/util/reduceToListState.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/reduceToListState'>;
}
declare module 'react-widgets/lib/util/scrollManager.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/scrollManager'>;
}
declare module 'react-widgets/lib/util/widgetHelpers.js' {
  declare module.exports: $Exports<'react-widgets/lib/util/widgetHelpers'>;
}
declare module 'react-widgets/lib/Widget.js' {
  declare module.exports: $Exports<'react-widgets/lib/Widget'>;
}
declare module 'react-widgets/lib/WidgetPicker.js' {
  declare module.exports: $Exports<'react-widgets/lib/WidgetPicker'>;
}
declare module 'react-widgets/lib/Year.js' {
  declare module.exports: $Exports<'react-widgets/lib/Year'>;
}
