// flow-typed signature: c1d6b51d6a4447778b87b2f5be93d652
// flow-typed version: <<STUB>>/react-tb-icons_v1.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tb-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tb-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tb-icons/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-tb-icons/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tb-icons/dist/index.es.js' {
  declare module.exports: $Exports<'react-tb-icons/dist/index.es'>;
}
declare module 'react-tb-icons/dist/index.js' {
  declare module.exports: $Exports<'react-tb-icons/dist/index'>;
}
