// flow-typed signature: 5e3bc14358abaeba66b55f19623a7144
// flow-typed version: <<STUB>>/react-widgets-moment_v^4.0.21/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-widgets-moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-widgets-moment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-widgets-moment/dist/react-widgets-moment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-widgets-moment/dist/react-widgets-moment.js' {
  declare module.exports: $Exports<'react-widgets-moment/dist/react-widgets-moment'>;
}
declare module 'react-widgets-moment/index' {
  declare module.exports: $Exports<'react-widgets-moment'>;
}
declare module 'react-widgets-moment/index.js' {
  declare module.exports: $Exports<'react-widgets-moment'>;
}
